name: Copy code to prod directories

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: 'Select input to update'
        required: true
        default: 'extraVars'
        options:
          - extraVars
          - inventory
          - deploymentManifest

jobs:
  update_and_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'update-${{ github.event.inputs.choice }}-inputs'

      - name: Create prod directories if not exist
        run: |
            for dir in extraVars inventory deploymentManifest; do
                if [ ! -d "prod/$dir" ]; then
                    mkdir -p "prod/$dir"
                    touch "prod/$dir/README.md"
                fi
            done
            ls -l prod
          
      - name: Copy files to prod directories
        run: |
          for file in $(pwd)/non-prod/${{ github.event.inputs.choice }}/*.json; do
            cp "$file" "$(pwd)/prod/${{ github.event.inputs.choice }}/$(basename $file)"
          done
          ls -l $(pwd)/prod/${{ github.event.inputs.choice }}
          
      - name: Create, push new branch with template changes
        uses: EndBug/add-and-commit@v9
        with:
          cwd: '$(pwd)/prod/${{ github.event.inputs.choice }}/$(basename $file)'
          add: '.'
          default_author: github_actions
          message: 'fix: copy files to prod directory'
          new_branch: 'update-${{ github.event.inputs.choice }}-inputs'
