name: Copy code to prod directories

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: 'Select input to update'
        required: true
        default: 'extraVars'
        options:
          - extraVars
          - inventory
          - deploymentManifest

jobs:
  update_and_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'update-${{ github.event.inputs.choice }}-inputs'

      - name: Verify Branch Creation  
        run: echo "Branch created:${{ steps.create_branch.outputs.branch }}"

      - name: Create prod directories if not exist
        run: |
            for dir in extraVars inventory deploymentManifest; do
                if [ ! -d "prod/$dir" ]; then
                    mkdir -p "prod/$dir"
                    touch "prod/$dir/README.md"
                fi
            done
            ls -l prod
            
      - name: Copy files to prod directories
        run: |
          for file in $GITHUB_WORKSPACE/non-prod/${{ github.event.inputs.choice }}/*.json; do
            cp "$file" "$GITHUB_WORKSPACE/prod/${{ github.event.inputs.choice }}/"
          done
          ls -l $GITHUB_WORKSPACE/prod/${{ github.event.inputs.choice }}
